title: Expense Tracker System
description: Software Engineering Project Report
remote_theme: just-the-docs/just-the-docs

url: https://zagrosbaban1.github.io
baseurl: /Expense-Tracker-System/report

search_enabled: true
heading_anchors: true

color_scheme: light

plugins:
  - jekyll-remote-theme

aux_links:
  "View Repository":
    - "https://github.com/Zagrosbaban1/Expense-Tracker-System"

footer_content: "Software Engineering project report for the Expense Tracker System."
